---
title: "2023 Session Schedule"
format:
  html:
    theme: yeti
editor: visual
output-file: "index"
---

April 10: CLI

April 11: Git/GitHub

April 12-13: Introductory Python

+-------------+------------------------------+------------------------+-------------------------------------+-------------+
|             | Monday                       | Tuesday                | Wednesday                           | Thursday    |
|             |                              |                        |                                     |             |
|             | April 17                     | April 18               | April 19                            | April 20    |
+=============+==============================+========================+=====================================+=============+
| 9:00-9:30   | x                            | Help Desk              | Help Desk                           | WiDS Tucson |
+-------------+------------------------------+------------------------+-------------------------------------+-------------+
| 9:30-10:00  | x                            | *Refresher Session*    | *Refresher Session Python*          | WiDS Tucson |
+-------------+------------------------------+------------------------+-------------------------------------+-------------+
| 10:00-10:30 | x                            | *Intermediate Session* | *Concurrent Intermediate R, Python* | WiDS Tucson |
+-------------+------------------------------+------------------------+-------------------------------------+-------------+
| 10:30-11:00 | x                            | *Intermediate Session* | *Concurrent Intermediate R, Python* | WiDS Tucson |
+-------------+------------------------------+------------------------+-------------------------------------+-------------+
| 11:00-11:30 | x                            | *Intermediate Session* | *Concurrent Intermediate R, Python* | WiDS Tucson |
+-------------+------------------------------+------------------------+-------------------------------------+-------------+
| 11:30-12:00 | x                            | *Intermediate Session* | *Intermediate Session*              | WiDS Tucson |
+-------------+------------------------------+------------------------+-------------------------------------+-------------+
| 12:00-12:30 | x                            | *Lunch Break*          | *Lunch Break*                       | WiDS Tucson |
+-------------+------------------------------+------------------------+-------------------------------------+-------------+
| 12:30-1:00  | x                            | *Lunch Break*          | *Lunch Break*                       | WiDS Tucson |
+-------------+------------------------------+------------------------+-------------------------------------+-------------+
| 1:00-1:30   | *Refresher Session: CLI^\*^* | *Introductory Session* | *Introductory Session*              | WiDS Tucson |
+-------------+------------------------------+------------------------+-------------------------------------+-------------+
| 1:30-2:00   | *Refresher Session: Git*     | *Panel*                | *Introductory Session*              | WiDS Tucson |
+-------------+------------------------------+------------------------+-------------------------------------+-------------+
| 2:00-2:30   | *Introductory R*             | *Introductory Session* | *Panel*                             | WiDS Tucson |
+-------------+------------------------------+------------------------+-------------------------------------+-------------+
| 2:30-3:00   | *Introductory R*             | *Introductory Session* | *Panel*                             | WiDS Tucson |
+-------------+------------------------------+------------------------+-------------------------------------+-------------+
| 3:00-3:30   | *Introductory R*             | *Intermediate Session* | *Intermediate Session*              | WiDS Tucson |
+-------------+------------------------------+------------------------+-------------------------------------+-------------+
| 3:30-4:00   | *Intermediate Session*       | *Intermediate Session* | *Intermediate Session*              | WiDS Tucson |
+-------------+------------------------------+------------------------+-------------------------------------+-------------+
| 4:00-4:30   | *Intermediate Session*       | *Intermediate Session* | *Intermediate Session*              | Hacky Hour  |
+-------------+------------------------------+------------------------+-------------------------------------+-------------+
| 4:30-5:00   | Wrap ups                     | Wrap ups               | Wrap up                             | Hacky Hour  |
+-------------+------------------------------+------------------------+-------------------------------------+-------------+

^*\**^ italicized sessions are suggestions

April 21: ICDI

## Suggested Sessions:

-   Introductory x

-   Intermediate x

-   Cross Discipline Data Science, Real World Data Science Applications

-   Notebooks - Quarto, YAML, Jupyters

-   AI

-   NLP

-   Open Source collaboration

-   SQL

-   How to "think like a coder"

## Schedule Suggestions:

-   consider concurrent zooms

-   include NAU, ASU social events
